version: '3.7'

services:

  web:
    container_name: 'tweekclone-app'
    image: 'tweekclone'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      # change this for a "real" app!
      POSTGRES_PASSWORD: 1234%Password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge